const address = import.meta.env.VITE_PERSONHOOD_LENDING_ADDRESS;

if (!address || address === '0x0000000000000000000000000000000000000000') {
  console.error('VITE_PERSONHOOD_LENDING_ADDRESS environment variable is not set or is zero address');
}

export const PERSONHOOD_LENDING_ADDRESS = address || '0x0000000000000000000000000000000000000000';

export const PERSONHOOD_LENDING_ABI = [
  {
    type: 'constructor',
    inputs: [{ name: '_protocolTreasury', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  // ============ Constants (public) ============
  {
    type: 'function',
    name: 'MIN_DEPOSIT',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_WEEKLY_PAYMENT',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'GRACE_PERIOD',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DISPUTE_TIMEOUT',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'OFFENCE_PENALTY_PERCENTAGE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BASIS_POINTS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'RENTAL_DURATION',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_OFFENCES',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_INVALID_DISPUTES',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  // ============ State Variables (public) ============
  {
    type: 'function',
    name: 'nextOfferId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextDisputeId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolTreasury',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  // ============ Core Functions ============
  {
    type: 'function',
    name: 'acceptOffer',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelRent',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimPayout',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createOffer',
    inputs: [
      { name: '_usageContext', type: 'string', internalType: 'string' },
      { name: '_weeklyPayment', type: 'uint256', internalType: 'uint256' },
      { name: '_deposit', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'offerId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'disputes',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'disputeId', type: 'uint256', internalType: 'uint256' },
      { name: 'offerId', type: 'uint256', internalType: 'uint256' },
      { name: 'renter', type: 'address', internalType: 'address' },
      { name: 'renterSignedRequest', type: 'bytes', internalType: 'bytes' },
      { name: 'expectedPayload', type: 'bytes', internalType: 'bytes' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
      { name: 'status', type: 'uint8', internalType: 'enum PersonhoodLending.DisputeStatus' },
      { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
      { name: 'disputeDeposit', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'offers',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'offerId', type: 'uint256', internalType: 'uint256' },
      { name: 'submitter', type: 'address', internalType: 'address' },
      { name: 'renter', type: 'address', internalType: 'address' },
      { name: 'usageContext', type: 'string', internalType: 'string' },
      { name: 'weeklyPayment', type: 'uint256', internalType: 'uint256' },
      { name: 'deposit', type: 'uint256', internalType: 'uint256' },
      { name: 'lockedPayment', type: 'uint256', internalType: 'uint256' },
      { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
      { name: 'rentedAt', type: 'uint256', internalType: 'uint256' },
      { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
      { name: 'status', type: 'uint8', internalType: 'enum PersonhoodLending.OfferStatus' },
      { name: 'totalRentals', type: 'uint256', internalType: 'uint256' },
      { name: 'lenderOffences', type: 'uint8', internalType: 'uint8' },
      { name: 'renterInvalidDisputes', type: 'uint8', internalType: 'uint8' },
      { name: 'activeDisputeId', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'removeExpiredOffer',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renewRental',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'renterActiveOffers',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'resolveDisputeTimeout',
    inputs: [{ name: '_disputeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'returnToMarket',
    inputs: [{ name: '_offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitDispute',
    inputs: [
      { name: '_offerId', type: 'uint256', internalType: 'uint256' },
      { name: '_renterSignedRequest', type: 'bytes', internalType: 'bytes' },
      { name: '_expectedPayload', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'submitRenterACK',
    inputs: [
      { name: '_disputeId', type: 'uint256', internalType: 'uint256' },
      { name: '_renterAck', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitSignature',
    inputs: [
      { name: '_disputeId', type: 'uint256', internalType: 'uint256' },
      { name: '_signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitterOffers',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updateOfferTerms',
    inputs: [
      { name: '_offerId', type: 'uint256', internalType: 'uint256' },
      { name: '_newWeeklyPayment', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ============ Events ============
  {
    type: 'event',
    name: 'ACKSubmitted',
    inputs: [
      { name: 'disputeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'renterAck', type: 'bytes', indexed: false, internalType: 'bytes' },
      { name: 'submittedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DisputeResolved',
    inputs: [
      { name: 'disputeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'resolution', type: 'uint8', indexed: false, internalType: 'enum PersonhoodLending.DisputeStatus' },
      { name: 'resolvedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DisputeSubmitted',
    inputs: [
      { name: 'disputeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'renter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'deadline', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'deposit', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferAccepted',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'renter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'rentedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'expiresAt', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'weeklyPayment', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferCreated',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'submitter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'usageContext', type: 'string', indexed: false, internalType: 'string' },
      { name: 'weeklyPayment', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'deposit', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'createdAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferExpired',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'expiredAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferRemoved',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'removedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferReturnedToMarket',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'returnedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OfferTermsUpdated',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'oldPayment', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'newPayment', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'updatedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OffenceCounted',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'party', type: 'address', indexed: true, internalType: 'address' },
      { name: 'offenceCount', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'offenceType', type: 'uint8', indexed: false, internalType: 'uint8' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PayoutClaimed',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'submitter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'payoutAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'penaltyAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'offences', type: 'uint8', indexed: false, internalType: 'uint8' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RentCancelled',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'renter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'refundAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'depositToTreasury', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'cancelledAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RentalRenewed',
    inputs: [
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newExpiresAt', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'additionalPayment', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SignatureSubmitted',
    inputs: [
      { name: 'disputeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'offerId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'signature', type: 'bytes', indexed: false, internalType: 'bytes' },
      { name: 'submittedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
] as const;
